### ISSUE TITLE
Delegating Blazegraph query logic to ExternalFullTextSearch

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#109]
Blazegraph supports [ExternalFullTextSearch](https://wiki.blazegraph.com/wiki/index.php/ExternalFullTextSearch), which is a way to query external fulltext indices from within SPARQL.

In this way we can delegate part of the query to external services, like `Elasticsearch` which might perform better in certain type of queries.

In this issue we are supposed to give examples of what to outsource to `Elasticsearch` and then create specific issues to implement each case.

I know we could delegate to `elasticsearch` the `total` count and some further counts which happens in `aggregations`.

What are your thoughts @MFSY @perspectivet @bogdanromanx

**Comment by MFSY** [comment]
Hi,
Delegating partially or totally the handling of some search cases (full text search, field value aggregation,...) to an external full text search engine like Elasticsearch is definitely valuable.

As far as I know,[ Blazegraph only supports Solr ](https://wiki.blazegraph.com/wiki/index.php/ExternalFullTextSearch) as external full text search service. To use it with Elasticsearch, a specific connector needs to be developed which will required a lot more work.

There is another option to explore with regard to using Elasticsearch in combination with Blazegraph and benefit from both world: [Jena ARQ Full text search](https://jena.apache.org/documentation/query/text-query.html).

According to the documentation two use cases are supported:

* "Find in the text index (Elasticsearch) and refine results":

First access to an Elasticsearch index in the query and get a number of items of interest; then further information is obtained about these items from the RDF data (Blazegraph).

* "Filter results via the text index"

By finding items of interest first in the RDF data (Blazegraph), the text search can be used to restrict the items found still further (in Elasticsearch).

**Comment by umbreak** [comment]
We are going to separate queries between triple store and ElasticSearch but not running them in combination for now. I close it. We can reopen it if we want to go on this path.
