### ISSUE TITLE
Blazegraph benchmarking

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#126]
We have to benchmark Blezegraph in order to find out how to tweak our queries in the best way and in order to know which are the current limitations for a specific setup. 

We have to explore query optimization, since there is apparently room for it [[1]](https://wiki.blazegraph.com/wiki/index.php/QueryHints) [[2]](https://wiki.blazegraph.com/wiki/index.php/QueryOptimization#Query_Optimization).

**Comment by wwajerowicz** [comment]
The quick summary of Blazegraph benchmarking:

- The main issue are the queries which large result sets ( e.g. `/data`) as this requires Blazegraph to read and sort all of them, total count is also causing this. However, we can't have pagination without it.
- The other issue are ACLs, especially `schemaGroup`, as they require two levels of traverals
- Fast disk is crucial for performance
- However, at some point the CPU becomes the bottleneck.
