### ISSUE TITLE
Update a domain is not implemented but It is described as an existing operation in docs

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#147]
[This section](https://bbp-nexus.epfl.ch/dev/docs/kg/api-reference/domains.html#update-a-domain) of the docs describes that it is possible to update a domain, when it isn't.

Either we remove it or we implement it. Event though right now domains can just contain description, which might be useless. #55 address the issue to add any valid metadata to a domain, and not only description.

**Comment by bogdanromanx** [comment]
As long as we don't change the id, we can safely update a domain; I would argue we should go with that.

**Comment by umbreak** [comment]
I think we should not implement that in v0 since we are transitioning to v1. So I will just delete this part of the documentation
