### ISSUE TITLE
Unify KG API for organization / domains with schemas / instances

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#15]
The current api for operating on resources is inconsistent:
```
/organizations/{org_id}
/organizations/{org_id}/domains/{domain_id}
/schemas/{org_id}/{domain_id}/{schema}/{version}
/data/{org_id}/{domain_id}/{schema}/{version}/{uuid}
```
It should either be (1):
```
/organizations/{org_id}
/domains/{org_id}/{domain_id}
/schemas/{org_id}/{domain_id}/{schema}/{version}
/data/{org_id}/{domain_id}/{schema}/{version}/{uuid}
```
or possibly even more interesting, just (2):
```
/data/nexus/core/organization/{version}/{org_id}
/data/nexus/core/domain/{version}/{domain_id}
/schemas/{org_id}/{domain_id}/{schema}/{version}
/data/{org_id}/{domain_id}/{schema}/{version}/{uuid}
```
Either way we go, we need to have the api consistent in between resources.

**Comment by umbreak** [comment]
I like more the option 1. Is more straight forwards from the point of view of API structure and resources. And it allows us to define in the future similar definitions for other resources

`/context/{orgId}/{domain_id}/...`

**Comment by umbreak** [comment]
We also need that API change if we want to be able to list all domains without filtering by organization, which now is not possible due to the API structure.

Another advantage of using that unified structure is that it will allow for the reuse of the extraction of the id's from the paths using `PathDirectives`

**Comment by bogdanromanx** [comment]
Agreed. I like the first option too. Especially since we're going to also introduce _context_s as the fifth top level resource.

Anyone else have other opinions? @MFSY, @samuel-kerrien, @hygt, @wwajerowicz ?

**Comment by umbreak** [comment]
Fixes by https://github.com/BlueBrain/nexus-kg/pull/46
