### ISSUE TITLE
Retrieve the list of shapes defined in a given schema

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#154]
A schema defines a collection of shapes (the items of the array shapes). It would be great to retrieve them when calling:

```shell
GET {{base}}/schemas/bbp/core/activity/v0.1.0/shapes
```

The expect result would be the list of shapes defined in the schema.

**Comment by umbreak** [comment]
Isn't a schema already a collection of shapes? Why to define two times the same resource?

This endpoint was already provided before and I developed that feature, but afterwards it was rejected with the exact argument I just gave you

**Comment by bogdanromanx** [comment]
I'm confused as well, would you like to be able to just present the ids of the shapes without their contents?

**Comment by umbreak** [comment]
maybe we could allow exploration of subresources through the URI? For example, once you hit the instance resource: .../data/org/dom/schema/v1.0.0/uuid/property
If we do that, on the schema side then  .../schemas/org/dom/schema/v1.0.0/shapes makes sense.
