### ISSUE TITLE
Add `context` as a first class resource in the KG

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#16]
Explicitly defining the context for each write / filtering operation is at least cumbersome. Having the ability to refer to a context in the system would significantly simplify the use of the platform.

To be discussed.

**Comment by MFSY** [comment]
+2 on this one. This is specially useful for the versioning and reuse of the SHACL specification @context. A schema payload is currently very long because of a mostly fixed SHACL context.
