### ISSUE TITLE
User defined context altered by adding nexus-kg specific resource context

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#163]
Currently all contexts include the resource context: {{base}}/contexts/nexus/core/resource/v0.1.0.

Even if the intention of adding the resource context in all resources managed by nexus (to define properties like nxv:rev for example) can be understood, a user defined context should not be altered.

**Comment by bogdanromanx** [comment]
I'm not sure I understand this: we don't want the resource context to be added in responses?

**Comment by MFSY** [comment]
The answer is yes when the responses are contexts themselves.
When extra properties (nxv:rev, nxv:deprecated,...) are added in an instance, it is easy for a client to ignore them when deserialising the instance. There is no practical way to ignore part of a context as far as I know.

**Comment by umbreak** [comment]
That's a consistency issue across different responses. All of them provide the platform managed metadata (`nxv:rev`, `nxv:deprecated`, ...) and for the response to be valid JSON-LD the resource context needs to be present.

Now, if someone wants to retrieve only its own payload, without the added platform managed metadata, maybe we need to signal this adding a query parameter or a subresource to the request. In this case the response would not need to have any of our contexts.

But I don't see any other way to do it without breaking consistency with the rest of the resources.

**Comment by bogdanromanx** [comment]
I agree with @umbreak on this; we can't exclude only the resource context because it would generate an invalid json-ld response. We either add a flag that removes all the service metadata, move the resource context in the header of the response (but that's quite unintuitive) or leave things as they are.
Thoughts?
