### ISSUE TITLE
Some contexts reference themselves

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#164]
There is a cycle in some contexts references e.g. {{base}}/contexts/nexus/core/resource/v0.1.0 context.

**Comment by umbreak** [comment]
The cyclick dependency is now as follows:

1. An instance/schema/context/domain/organization is fetched and it contains the context for resource: "https://bbp-nexus.epfl.ch/dev/v0/contexts/nexus/core/resource/v0.1.0"
2. The context in that link contains again a link to "https://bbp-nexus.epfl.ch/dev/v0/contexts/nexus/core/resource/v0.1.0"
