### ISSUE TITLE
Load all nexus core contexts at boot time

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#169]
Nexus-kg defines many contexts mainly in [nexus-common](https://github.com/BlueBrain/nexus-commons/tree/master/modules/schemas/src/main/resources/contexts/nexus/core).

It would be great if those core contexts are loaded and made available at boot time.

**Comment by umbreak** [comment]
This is dup from the issue: https://github.com/BlueBrain/nexus-kg/issues/138
I will close this.
