### ISSUE TITLE
Redirection / rewriting for deprecated instances with sameAs

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus-kg#176]
After some time, we will need to migrate/upgrade our instances to new (evolved) schema versions. As soon as the old version is not in use by any client anymore, we would like to deprecate its instances. for the moment, we have planned to link the old instances and their new counterparts with owl:sameAs.

Since these old (to be deprecated) instances might still be linked to others, we either would need to adapt all of those links to an appropriate (non-deprecated) "sameAs" version or we would think of having a redirection to the/a currently active instance. In both cases, it would be nice to have support of nexus (by providing convenience functionality of adapting linked instances or by interpreting the "owl:sameAs" (or whatever link you prefer) and providing redirection functionality).

**Comment by umbreak** [comment]
We are planning to provide a way to migrate instances across different schema versions. We have ongoing discussions on how to implement this.

**Comment by umbreak** [comment]
We are putting our efforts on `v1` release for the next sprints. After that we will discuss what's the best way to bring this feature to Nexus.
