### ISSUE TITLE
ElasticSearch indexing strategy

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#188]
Since we are going to separate listing (and simple querying) concerns from queries which require path traversals we need another indexer to do the job. We are choosing ElasticSearch.

The basic indexing strategy which comes in place is to index the whole customer payload for every resource (plus it's relationship to other resources).

For relating resources we could use (organization -> domain -> schema -> instance) the [parent-child relationship](https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child.html).

Thoughts @bogdanromanx @MFSY ?

**Comment by bogdanromanx** [comment]
It's dangerous to use parent-child to model the resource nesting due to:

> the parent document and all of its children must live on the same shard

I would recommend trying a flat structure instead.

**Comment by umbreak** [comment]
In the end the approach taken is as follows:
There will be an index for each organization and for each domain. Schemas, Contexts and Instances will be indexed inside the domain index. In this case we can isolate the query impact across domains.
Each event will be stored and the extra metadata required (createdAtTime, rev, orgId, ...) will be appended to it.
