### ISSUE TITLE
Add config subresource on instances in order to enable/disable binary upload

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#19]
Right now attachment on an instance is always allowed. We need a configuration parameter to enable or disable this feature.

**Comment by bogdanromanx** [comment]
I would argue that the `config` sub-resource should be described by schemas, domains and organizations, not an instance.
Additionally, they should also describe and `instantiation` flag to control whether new instances can be created.
I would recommend naming the binary upload flag as `attachments`.

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/107)
