### ISSUE TITLE
Bootstrap platform schemas when starting services

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#197]
The schemas defined in [commons-schemas](https://github.com/BlueBrain/nexus-commons/tree/master/modules/schemas/src/main/resources) and [kg-schemas](https://github.com/BlueBrain/nexus-kg/tree/master/modules/kg-schemas/src/main/resources/schemas/nexus) should be created (if they do not already exist) when booting up the service

**Comment by umbreak** [comment]
Moved to v1 milestone implemented with assets or as a specific project resolver

**Comment by MFSY** [comment]
The nexus core contexts should also be loaded and published.

**Comment by umbreak** [comment]
Close this because it is now handled by: https://github.com/BlueBrain/nexus-kg/issues/138
