### ISSUE TITLE
Enable field-based search

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-kg#226]
E.g. perform full text search on 'label' field inside 'brainRegion' property:

{
         "@context": [...],
         "@id": "...",
         "@type": [...],
         "**brainRegion**": {
                     "@id": "...",
                     "**label**": "primary somatosensory cortex"
         }
}

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/102)
