### ISSUE TITLE
Use nexus/core/resource/v0.2.0 as default nexus resource base context

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#236]
When a new resource (instance, schema, context) is created, nexus adds the nexus/core/resource context which provides prefix mappings to:

* distribution
* id
*type
*links

The current nexus/core/resource/v0.1.0 context is not valid as it leads to cycle when resolving the referenced contexts. It is now replaced by [nexus/core/resource/v0.2.0](https://github.com/BlueBrain/nexus-commons/blob/master/modules/schemas/src/main/resources/contexts/nexus/core/resource/v0.2.0.json) which should be used from now on.

Also a nexus/core/resource/vX.X.X context should not referenced itself or any other version of nexus/core/resource

**Comment by umbreak** [comment]
It will be replaced by [0.3.0](https://github.com/BlueBrain/nexus-commons/blob/v0/modules/schemas/src/main/resources/contexts/nexus/core/resource/v0.3.0.json)

**Comment by umbreak** [comment]
Now it is pointing to v0.3.0 and the JSON-LD Playground can resolve it. I close this
