### ISSUE TITLE
Add a SHACL documentation section

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#24]

**Comment by bogdanromanx** [comment]
@MFSY is this issue still in progress?

**Comment by danbri** [comment]
Hi. I wanted to point to what you're doing with SHACL but couldn't find a good link, so I'll just point to your issue tracker for now! https://github.com/BlueBrain/nexus-kg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+shacl ...
