### ISSUE TITLE
Attachments download

### ISSUE THREAD

**Issue by YanLobat** [BlueBrain/nexus-kg#258]
I faced with an issue when I tried to download [attachment](https://bbp-nexus.epfl.ch/dev/v0/data/bbp/electrophysiology/trace/v0.1.0/01dde9fc-8504-413e-9e48-23122b9dfbec/attachment). Filename is not the proper one. Can you fix this according to originalfilename field? Many thanks

**Comment by umbreak** [comment]
We can accomplish that, when using browsers that support [RFC 6266](https://tools.ietf.org/html/rfc6266) by providing the HTTP HEADER: `Content-Disposition: attachment; filename="example.html"`
