### ISSUE TITLE
Blazegraph update hangs with DeleteWithQuerySteamingTask

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#262]
Performing sequential delete and inserts (100+) into BlazeGraph during indexing causes BlazeGraph to  stop responding; looking at the queries we can see a long running `DeleteWithQuerySteamingTask` that never completes. The number of updates required varies depending on the environment configuration.
To make matters worse, because the query does not finish the servlet container interrupts the request without killing the task so `kg` will notice failed request and retry. This causes subsequent `DeleteWithQuerySteamingTask` being created which eventually makes BlazeGraph unresponsive, I suspect because of ThreadPool exhaustion.

The problem does not manifest itself with inserts, only updates which the client implements as (delete, insert) pairs.

**Comment by olinux** [comment]
The following script recreates the problem in direct interaction with blazegraph. It currently shows the following behaviour:
Blazegraph executable jar, empty journal: works
Blazegraph executable jar, initial dataload of HBP: fails
Blazegraph in Jetty, empty journal: fails
Blazegraph executable jar, journal from failing Jetty: works

I'm investigating now what the differences might be.

`#!/bin/bash

curl -X POST 'http://localhost:9999/blazegraph/namespace/kg/sparql?context-uri=https%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fv0%2Fdata%2Fgraphs%2Fdata%2Ftest%2Fcore%2Ftest%2Fv0.0.1%2Fc755d7f9-8752-4ae4-85a2-84bb780b979a' -H 'cache-control: no-cache' -H 'content-type: application/ld+json' -d '{"@context":{"schema":"http://schema.org/","test":"http://test.org/"},"@id":"https://nexus-dev.humanbrainproject.org/v0/data/test/core/test/v0.0.1/c755d7f9-8752-4ae4-85a2-84bb780b979a","@type":["test:Test"],"http://www.w3.org/1999/02/22-rdf-syntax-ns#type":{"@id":"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/Instance"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/deprecated":false,"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/domain":{"@id":"https://nexus-dev.humanbrainproject.org/v0/domains/test/core"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/organization":{"@id":"https://nexus-dev.humanbrainproject.org/v0/organizations/test"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/rev":2,"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/schema":{"@id":"https://nexus-dev.humanbrainproject.org/v0/schemas/test/core/test/v0.0.1"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/updatedAtTime":{"@type":"http://www.w3.org/2001/XMLSchema#dateTime","@value":"2018-03-08T15:25:03.946Z"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/uuid":"c755d7f9-8752-4ae4-85a2-84bb780b979a","schema:name":"A test"}'


for i in $(seq 1 $1)
  do
    echo "DELETE $i"
    curl -X DELETE 'http://localhost:9999/blazegraph/namespace/kg/sparql?query=CONSTRUCT%20%0A%20%20%7B%20%0A%20%20%20%20%3Fs%20%3Fp%20%3Fo%20.%0A%20%20%7D%0AWHERE%0A%20%20%7B%20GRAPH%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fv0%2Fdata%2Fgraphs%2Fdata%2Ftest%2Fcore%2Ftest%2Fv0.0.1%2Fc755d7f9-8752-4ae4-85a2-84bb780b979a%3E%0A%20%20%20%20%20%20%7B%20%3Fs%20%20%3Fp%20%20%3Fo%0A%20%20%20%20%20%20%20%20FILTER%20(%20(%20(%20(%20(%20(%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FcreatedAtTime%3E%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FschemaGroup%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2ForiginalFileName%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FmediaType%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FcontentSize%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FdigestAlgorithm%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2Fdigest%3E%20)%20)%0A%20%20%20%20%20%20%7D%7D%0A'
   echo "POST $i"
   curl -X POST 'http://localhost:9999/blazegraph/namespace/kg/sparql?context-uri=https%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fv0%2Fdata%2Fgraphs%2Fdata%2Ftest%2Fcore%2Ftest%2Fv0.0.1%2Fc755d7f9-8752-4ae4-85a2-84bb780b979a' -H 'cache-control: no-cache' -H 'content-type: application/ld+json' -d "{\"@context\":{\"schema\":\"http://schema.org/\",\"test\":\"http://test.org/\"},\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/data/test/core/test/v0.0.1/c755d7f9-8752-4ae4-85a2-84bb780b979a\",\"@type\":[\"test:Test\"],\"http://www.w3.org/1999/02/22-rdf-syntax-ns#type\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/Instance\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/deprecated\":false,\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/domain\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/domains/test/core\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/organization\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/organizations/test\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/rev\":$i,\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/schema\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/schemas/test/core/test/v0.0.1\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/updatedAtTime\":{\"@type\":\"http://www.w3.org/2001/XMLSchema#dateTime\",\"@value\":\"2018-03-08T15:25:03.946Z\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/uuid\":\"c755d7f9-8752-4ae4-85a2-84bb780b979a\",\"schema:name\":\"A test\"}"


done
`

**Comment by olinux** [comment]
Additionally: Tests with DELETE as its done in the UI  ```
#not compatible with the query above - just an example
curl "$ENDPOINT" -H 'Content-Type: application/x-www-form-urlencoded'  --data 'update=DELETE+WHERE+%7BGRAPH+%3Chttp%3A%2F%2Ffoo%3E+++++++%7B%3Fs+%3Fp+%3Fo+%7D%7D' ```seemed to behave better

**Comment by bogdanromanx** [comment]
By `behave better` do you mean it's sidestepping the issue?

**Comment by olinux** [comment]
Yes - at least as part of the standalone script (I wasn't able to test the full chain with the real data). But it seems like this kind of query doesn't trigger a DeleteTask and therefore doesn't lock up.

**Comment by olinux** [comment]
Steps to reproduce (tested on a new machine that never had anything to do with blazegraph):

``` 
#install jetty
sudo apt-get install jetty9
cd /var/lib/jetty9/webapps

#download blazegraph and make it readable / writable for jetty
sudo wget https://github.com/blazegraph/database/releases/download/BLAZEGRAPH_RELEASE_2_1_4/blazegraph.war
sudo mkdir blazegraph
cd blazegraph
sudo unzip ../blazegraph.war
cd ..
sudo rm blazegraph.war
sudo chown -R jetty blazegraph/ 
sudo sed -i 's/bigdata.jnl/\/tmp\/bigdata.jnl/g' blazegraph/WEB-INF/classes/RWStore.properties
```
Set your memory in /etc/default/jetty9
`JAVA_OPTIONS="-Xmx2014m - Djava.awt.headless=true"`

`sudo service jetty9 start`

navigate in your browser to http://localhost:8080/blazegraph/#namespaces
create namespace called "kg" with "quads" and "full text index"

create a shell script with the content:
```
curl -X POST 'http://localhost:8080/blazegraph/namespace/kg/sparql?context-uri=https%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fv0%2Fdata%2Fgraphs%2Fdata%2Ftest%2Fcore%2Ftest%2Fv0.0.1%2Fc755d7f9-8752-4ae4-85a2-84bb780b979a' -H 'cache-control: no-cache' -H 'content-type: application/ld+json' -d '{"@context":{"schema":"http://schema.org/","test":"http://test.org/"},"@id":"https://nexus-dev.humanbrainproject.org/v0/data/test/core/test/v0.0.1/c755d7f9-8752-4ae4-85a2-84bb780b979a","@type":["test:Test"],"http://www.w3.org/1999/02/22-rdf-syntax-ns#type":{"@id":"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/Instance"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/deprecated":false,"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/domain":{"@id":"https://nexus-dev.humanbrainproject.org/v0/domains/test/core"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/organization":{"@id":"https://nexus-dev.humanbrainproject.org/v0/organizations/test"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/rev":2,"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/schema":{"@id":"https://nexus-dev.humanbrainproject.org/v0/schemas/test/core/test/v0.0.1"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/updatedAtTime":{"@type":"http://www.w3.org/2001/XMLSchema#dateTime","@value":"2018-03-08T15:25:03.946Z"},"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/uuid":"c755d7f9-8752-4ae4-85a2-84bb780b979a","schema:name":"A test"}'


for i in $(seq 1 $1)
  do
    echo "DELETE $i"
    curl -X DELETE 'http://localhost:8080/blazegraph/namespace/kg/sparql?query=CONSTRUCT%20%0A%20%20%7B%20%0A%20%20%20%20%3Fs%20%3Fp%20%3Fo%20.%0A%20%20%7D%0AWHERE%0A%20%20%7B%20GRAPH%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fv0%2Fdata%2Fgraphs%2Fdata%2Ftest%2Fcore%2Ftest%2Fv0.0.1%2Fc755d7f9-8752-4ae4-85a2-84bb780b979a%3E%0A%20%20%20%20%20%20%7B%20%3Fs%20%20%3Fp%20%20%3Fo%0A%20%20%20%20%20%20%20%20FILTER%20(%20(%20(%20(%20(%20(%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FcreatedAtTime%3E%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FschemaGroup%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2ForiginalFileName%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FmediaType%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FcontentSize%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2FdigestAlgorithm%3E%20)%20)%20%26%26%20(%20%3Fp%20!%3D%20%3Chttps%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fvocabs%2Fnexus%2Fcore%2Fterms%2Fv0.1.0%2Fdigest%3E%20)%20)%0A%20%20%20%20%20%20%7D%7D%0A'
   echo "POST $i"
   curl -X POST 'http://localhost:8080/blazegraph/namespace/kg/sparql?context-uri=https%3A%2F%2Fnexus-dev.humanbrainproject.org%2Fv0%2Fdata%2Fgraphs%2Fdata%2Ftest%2Fcore%2Ftest%2Fv0.0.1%2Fc755d7f9-8752-4ae4-85a2-84bb780b979a' -H 'cache-control: no-cache' -H 'content-type: application/ld+json' -d "{\"@context\":{\"schema\":\"http://schema.org/\",\"test\":\"http://test.org/\"},\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/data/test/core/test/v0.0.1/c755d7f9-8752-4ae4-85a2-84bb780b979a\",\"@type\":[\"test:Test\"],\"http://www.w3.org/1999/02/22-rdf-syntax-ns#type\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/Instance\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/deprecated\":false,\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/domain\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/domains/test/core\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/organization\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/organizations/test\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/rev\":$i,\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/schema\":{\"@id\":\"https://nexus-dev.humanbrainproject.org/v0/schemas/test/core/test/v0.0.1\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/updatedAtTime\":{\"@type\":\"http://www.w3.org/2001/XMLSchema#dateTime\",\"@value\":\"2018-03-08T15:25:03.946Z\"},\"https://nexus-dev.humanbrainproject.org/vocabs/nexus/core/terms/v0.1.0/uuid\":\"c755d7f9-8752-4ae4-85a2-84bb780b979a\",\"schema:name\":\"A test\"}"


done
```
And execute it with 2000 iterations
```
your_shell.sh 2000
```

Go to http://localhost:8080/blazegraph/#status and see how a "DeleteWithQuery" shows up that doesn't disappear

**Comment by bogdanromanx** [comment]
Thanks for the steps to reproduce. I'm working on changing the delete/insert using this other endpoint.

**Comment by olinux** [comment]
Fixed by https://github.com/blazegraph/database/issues/81

**Comment by olinux** [comment]
Works with 0.9.8
