### ISSUE TITLE
Embed query results context in search results

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#27]
When searching or filtering data in the platform the response provided by the service does not include an LD context.

The following context should be added to responses (as described by the documentation):
```
{
  "@context": {
    "nxv": "https://nexus.example.com/v0/voc/nexus/core/",
    "nxs": "https://nexus.example.com/v0/voc/nexus/search/",
    "total": "nxs:total",
    "results": "nxs:results",
    "resultId": "nxs:resultId",
    "maxScore": "nxs:maxScore",
    "score": "nxs:score",
    "source": "nxs:source",
    "links": "nxv:links",
    "rel": "nxv:rel",
    "href": "nxv:href"
  }
}
```

**Comment by MFSY** [comment]
I would suggest the following two options here: 
 1 - one vocabulary (@vocab) for all the terms above to which source specific context can be added:

"@context": {
	"@vocab": "https://nexus.example.com/v0/voc/nexus/core/",
        "resultSpecificPrefix": "http://resultSpecificNamespace.com/"
  }

 2 - an external context (stored in nexus-kg) for the search result vocabulary and then refer to it locally:

"@context": {
	"https://nexus.example.com/v0/contexts/nexus/core/vX.X.X",
        {
            "resultSpecificPrefix": "http://resultSpecificNamespace.com/"
        }
  }

**Comment by umbreak** [comment]
The correct context is already added to the search responses, as far as I'm aware of. I'm closing this issue.
