### ISSUE TITLE
Status for indexation settlement

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus-kg#274]
For programmatic access, it would be great to have some service to ask Nexus if the indexation is settled / if a (list of) instances are available in all indexes.
If I e.g. have two scripts uploading data sequentially and the second of those scripts relies on data of the first one to be fully indexed, I need to postpone the execution of the second until we're sure that it's available. Since blazegraph is typically the last one, we currently do this by a workaround (requesting the instance from nexus by a filter-path query to make sure the result originates from blazegraph) - but it would be great to remove that "implicit" knowledge underlying this mechanism and just ask Nexus "is this instance indexed everywhere?".

**Comment by bogdanromanx** [comment]
Interesting idea @olinux, I guess it's not complicated to implement on a per instance basis, but the status of indexing into a system as a whole could only be expressed in terms of "how far behind is this index stream compared to the event store log"... i.e.: indexing to blazegraph is ~50 events behind.

v1 implementation will most likely deal with per project indexing streams which would provide a more accurate view for this kind of status.

It would be very beneficial to brain storm how would the operational api would look like...

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/97)
