### ISSUE TITLE
Specify error response message when using special characters in full text search query

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus-kg#279]
Using special characters in the full text filter query value (e.g. double quotes: https://nexus/v0/data?q="JY160309") currently results in the following generic error response message: "There was an internal server error."

**Comment by bogdanromanx** [comment]
We need to validate / encode query params that we send to third parties...

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/96)
