### ISSUE TITLE
Support Project level configuration for queries

### ISSUE THREAD

**Issue by olinux** [BlueBrain/nexus-kg#280]
During the evolution of the graph, there will be a growing number of deprecated resources. It would be nice, if the API would exclude them by default because typically, you're only interested in the still existing instances. Adding the deprecated=false parameter to every query seems like an unnecessary overhead in most cases. 
I still think it's a great feature to be able to enable the visibility of deprecated resources - but from a client standpoint, this should rather be an opt-in than an opt-out.

Edited (changed title):
> deprecated=false as default

**Comment by umbreak** [comment]
I think a good approach here is to have `default configuration settings`, either per `account` or per `project`. And a lot of the filtering, sorting, deprecation, returned fields, etc, should be picked from those defaults and only overridden when the customer explicitly specifies it.

**Comment by bogdanromanx** [comment]
Both suggestions sound good; since we don't have a "consumer" service there's no place to save user preferences, maybe we could use admin for that... I don't know if saving query preferences against a project is the right thing to do. Thoughts?

**Comment by umbreak** [comment]
I think user configuration would make more sense in this case, rather than project. But for that we would need to create a top level resource on `admin`. Something to discuss on a meeting.

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/95)
