### ISSUE TITLE
Full text search not working if the start is not correct (even with *)

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/nexus-kg#281]
I'm trying to full search by part of the entity name.

BASE = https://nexus-int.humanbrainproject.org/v0/data/brainsimulation/simulation/memodel/v0.1.1
We have an entity
BASE/a27fdf49-1798-4b76-99d5-4cf8afe3c31b

This entity has the **name** attribute `CA1_int_cAC_031031AM1_20180201104443`

If I query:
`BASE?q=CA1_int_cAC_031031AM1_20180201104443` -> Works
`BASE?q=*CA1_int_cAC_031031AM1_20180201104443*` -> Works
`BASE?q=*CA1_int_cAC_031031AM1*` -> Works
`BASE?q=*031031AM1_20180201104443*` -> NOT Working (I removed some part from the beginning)

**Comment by bogdanromanx** [comment]
The issue is caused by the blazegraph behaviour as described here: https://wiki.blazegraph.com/wiki/index.php/FullTextSearch#Regular_Expressions

**Comment by PolinaShichkova** [comment]
I'm also interested in this. Do you know when to expect this to be available? Thank you!

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/110)
