### ISSUE TITLE
Documentation update to reflect curl request handling

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-kg#283]
The API documentation e.g. [here](https://bbp-nexus.epfl.ch/staging/docs/kg/api-reference/queries.html) contains curl commands which probably do not URL encode the query parameters. The examples do not work (see also [slack comment](https://bbpneuroinformatics.slack.com/archives/C0K1M579T/p1522317769000328)).

**Comment by umbreak** [comment]
Yes true. It isn't url encoded in purpose because of readability. However, since we have the tab for `query payload`, it might make sense to actually encode the payload on the curl tab. @bogdanromanx @hygt @wwajerowicz some ideas?

**Comment by bogdanromanx** [comment]
Agreed! ;)
