### ISSUE TITLE
Documentation 'breadcrumb' on the right side does not reflect the user's position

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-kg#284]
Example for the page https://bbp-nexus.epfl.ch/staging/docs/kg/api-reference/contexts.html:

Open the tab 'Payload' in the first example and scroll down the page. The breadcrumb on the right side shows you NOT where you are...

![selection_281](https://user-images.githubusercontent.com/12729291/38312262-965007a6-3821-11e8-94f8-2450fe16549f.png)

**Comment by umbreak** [comment]
Yes. This is a [known bug](https://github.com/lightbend/paradox/issues/140) on the documentation plugin we are using. There is a work around for it, as described on the issue's comment, however we haven't tried that yet
