### ISSUE TITLE
Suggestion: Change "links"-array from the search result to a JSON-object

### ISSUE THREAD

**Issue by dkutny** [BlueBrain/nexus-kg#29]
As of now, when you have a search result, you receive an array with different links, i.e. when you visit
https://bbp-nexus.epfl.ch/dev/v0/organizations?from=1&size=5
you receive the following array of links
```json
"links": [{
        "rel": "self",
        "href": "https://bbp-nexus.epfl.ch/dev/v0/organizations?from=1&size=5"
    }, {
        "rel": "previous",
        "href": "https://bbp-nexus.epfl.ch/dev/v0/organizations?from=0&size=1"
    }]
```
I would suggest to use an object instead of an array with "rel" being the key. This would allow you to parse it and, for example, use it directly in Python as a dictionary, i.e.
```python
html = '<a href="' + links["previous"] + '">Previous Page</a>'
```

**Comment by bogdanromanx** [comment]
Thanks @dkutny for submitting this issue. To be honest I have mixed feelings about modifying the format for links.
I definitely understand the usability issue with using an array instead of a simple dictionary, but:

1. How would you recommend handling the case where the `links` needs to contain 2 related resources with the same type of relationship? Would you say a nested href array is ok?
```
"links": {
  "single-rel": "https://uri/to/single",
  "multiple-rel": [
    "https://uri/to/multiple1",
    "https://uri/to/multiple2"
  ]
}
```

2. The links value represents a collection of possibly unrelated link objects with a well defined format; turning that into a dictionary does not convey that (I'd say). I'm not familiar with python, but in scala you could do something like this to turn a list of tuples into a dictionary of _Strings to List of Strings_ (aka a multi map):
```
val links: List[(String, String)] = _
val dict: Map[String, List[String]] = links.groupBy(_._1).mapValues(_.map(_._2))
```
Is there a similar thing in python?

@MFSY, @umbreak, @samuel-kerrien: could you please share your thoughts on this?

**Comment by umbreak** [comment]
There are several possibilities as pointed out [here](https://sookocheff.com/post/api/on-choosing-a-hypermedia-format/).
We should follow the JSON-LD way. And as far as I understand it, it implies having a subject, predicate and object for every resource. Probably @MFSY can make a suggestion on it

**Comment by MFSY** [comment]
Both serializations for 'links' are syntactically valid with respect to JSON-LD. 
I believe it's more related to which media type one adhere to for a REST API. 

HAL supports a **'_links'** object (the rels being the keys) as @dkutny suggested while other media types seem to support a **'links'** array as currently implemented in the Nexus KG API. 

Also note that JSON-LD media type doesn't really need (nor enforce) the use of a 'links' object or array per se to relate entities. It comes with built in and native support of linking entities through properties (a link between two entities is a triple: entity_1 - relation - entity_2 ). But I think that a 'links' is useful to explicitly adhere to the HATEOAS principles.
 
Now I agree that depending on the language chosen to consume the API one may find one serialization more suitable then the other.

I would go with what is currently implemented in Nexus KG (links as an array).

**Comment by dkutny** [comment]
@MFSY I do think that in most cases the '_links' approach would be more suitable for users. You will always have to iterate through the array, which is always more complicated than accesssing it directly, at least in the languages I can think of (Python, JavaScript, PHP).
@bogdanromanx Yes, I do like the approach of the 'multiple-rel' array, but I'm not sure if it breaks compatibility with HAL.

**Comment by umbreak** [comment]
In the end we decided to use the following representation for links

```json
"links": {
    "@context": "{{base}}/contexts/nexus/core/links/v0.1.0",
    "downloadURL": [
      "{{base}}/data/orgId/domainId/schema/v0.1.0/aab2fb8f-2c77-4dfa-84aa-383768832f3e/attachment?rev=1"
    ],
    "self": "{{base}}/data/orgId/domainId/schema/v0.1.0/aab2fb8f-2c77-4dfa-84aa-383768832f3e",
    "schema": "{{base}}/data/orgId/domainId/schema/v0.1.0/aab2fb8f-2c77-4dfa-84aa-383768832f3e"
  },
```

We'll implement that in the following sprint
