### ISSUE TITLE
Routes for static resource (contexts, schemas)

### ISSUE THREAD

**Issue by wwajerowicz** [BlueBrain/nexus-kg#304]

**Comment by wwajerowicz** [comment]
The idea to make it work would be to have a component in `service-commons` that given a path to a resource directory with following contents:
```
/contexts/
  context1.json
  context2.json
/schemas/
  schema1.json
  schema2.json
```
would expose following resources in the HTTP api
```
/{prefix}/contexts/context1
/{prefix}/contexts/context2
/{prefix}/schemas/schema1
/{prefix}/schemas/schema2
```

The `@id` of the resource would be injected and be the same as the URL at which it would be available.
Since those are public and will be accessible in the GitHub repo anyway, there's no requirements for ACLS.

Any thoughts @MFSY @bogdanromanx @umbreak @hygt ?

**Comment by umbreak** [comment]
Created from issue https://github.com/BlueBrain/nexus-kg/issues/273

**Comment by bogdanromanx** [comment]
We need to think about the addresses and ids of these resources. @MFSY could you please advise on what are the appropriate ids and the location of these resources in the API? 

- shacl schema schema
- resource schema
- search context
- error context
- resource context

@wwajerowicz I agree that we shouldn't protect these resources with ACLs. We should also bind the routes such that the static ones take priority over routes for runtime resources.

**Comment by umbreak** [comment]
@wwajerowicz this issue can be moved to the appropriate project (nexus-service)
