### ISSUE TITLE
Description of creating a schema in v0 documentation missing 

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-kg#314]
In the documentation for the v0 API regarding the schema here:

    https://bbp-nexus.epfl.ch/staging/docs/kg/api-reference/schemas.html

it seems that some description is missing regarding how the version must be defined ("Create a schema").

I suggest to add a line like the other lines explaining `OrgId`, `DomId`, ... so that its clear a version must be something like `v1.0.0` ...

**Comment by umbreak** [comment]
Isn't that already stated in the line:

> The version is constrained by the [semantic format](https://semver.org/) and it adds versioning information to the schema.

**Comment by umbreak** [comment]
We probably just need to set the version field in the same way we set the other fields.
