### ISSUE TITLE
Cannot Update Published Schema

### ISSUE THREAD

**Issue by PolinaShichkova** [BlueBrain/nexus-kg#315]
Dear Nexus team,
I tried to update my published schema and publish updated version analogically to the instance update, but got the following error:
ERROR:pyxus.utils:ERROR PUT 400: https://bbp-nexus.epfl.ch/staging/v0/schemas/ngvdemo/core/reaction/v0.1.0?rev=2 <Response [400]>
...
"code":"CannotUpdatePublished"
...
400 Client Error: Bad Request for url: https://bbp-nexus.epfl.ch/staging/v0/schemas/ngvdemo/core/reaction/v0.1.0?rev=2

Please, could you support published schema update?

Thank you!

**Comment by umbreak** [comment]
This is a feature of Nexus to enforce immutability. After published, a schema cannot be updated.

We are working on a `v1` API where the publishing concept changes (for tags) and there it would be possible to make further updates.

**Comment by umbreak** [comment]
This feature will work in v1 since there is not (yet) a concept of publish but a concept of tagging. Development in `v0` is only going to be focused on bug fixing and not on features and we consider this as a feature.
