### ISSUE TITLE
Documentation for BBP-SHACL  renders incomplete on Firefox

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus-kg#316]
On firefox images of the documentation do not render correctly (they do in chrome):

![selection_324](https://user-images.githubusercontent.com/12729291/40105143-6a7501bc-58f2-11e8-8940-5639a764f370.png)

Link: https://bbp-nexus.epfl.ch/dev/schema-documentation/documentation/shacl-schemas.html#target-declaration

**Comment by mdupont** [comment]
Which version of Firefox? On my machine I get the same result, see below with Firefox on the left side and Chrome on the right side.
![screen shot 2018-05-16 at 10 35 51](https://user-images.githubusercontent.com/651209/40106033-f875a3ca-58f4-11e8-8f52-2af63d10a62b.png)
