### ISSUE TITLE
Management of Agent and User in Nexus

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus-kg#346]
This thread of email was originally exchanged by Jean Denis Courcol and Francois Sy:

Dear All,

I would like to understand better your strategy with respect to user and
agent identification in Nexus (at least in the BBP context).

Let 's say a experimenter (let's say Ying) has created some morphology
reconstructions. How is that agent representing Ying created in Nexus ?
What information are provided ? Who is providing these information ? How
is it uniquely identified (gaspar id, e-mail ...) ?

Let's say a user performs some analysis through one of our software
(let's say Ying or Lida). How do we query the system to know if that
agent is already in the system: How is the agent identified ? Keep in
mind that the only user identification element we have on the software
side is the authentication token.

If the agent is not in the system, how is it going to be created ?

Regards,

Jean-Denis

**Comment by samuel-kerrien** [comment]
Dear Jean-Denis

Thank you for your questions. Here are some answers.

1. Let 's say an experimenter (let's say Ying) has created some morphology reconstructions. How is that agent representing Ying created in Nexus ? What information are provided ? Who is providing these information ?

A user can be represented in Nexus using the following person schema (open the links to see the properties): https://github.com/INCF/neuroshapes/blob/master/modules/commons/src/main/resources/schemas/neurosciencegraph/commons/person/v0.1.0.json
You can find an html documentation of it: http://nexus.apps.bbp.epfl.ch/dev/datamodel/shape-bbpcorepersonv010shapespersonshape.html

2. If the agent is not in the system, how is it going to be created?

Just do:

curl -H "Content-Type: application/json" \
   -H "Authorization: Bearer <ACCESS_TOKEN>" \
  --request POST \
  --data '{"givenName":"Ying","familyName":"Shi","email":"ying.shi@epfl.ch"}' \
  https://bbp.epfl.ch/nexus/v0/schemas/your_project/contributor/person/v0.1.0

Of course the schema https://bbp.epfl.ch/nexus/v0/schemas/your_project/contributor/person/v0.1.0 needs to be created first.

3. How a user agent is uniquely identified (gaspar id, e-mail ...) ?

As you can see, we don't store all contributors in one place and their (nexus generated) identifiers changes if you create them in different organizations or domains. The reason is we can't reuse identifiers in Nexus v0 (can't wait for v1). In Nexus v1 this will be solved. But meanwhile, we recommend to identify the user agents by email (not always accurate and persistent but works most of the time). The email uniqueness is not enforced in Nexus, so duplication can happen. It is the responsibility of the data integrator to check for duplication before pushing data in Nexus v0.

4. Let's say a user performs some analysis through one of our software
    (let's say Ying or Lida). How do we query the system to know if that
    agent is already in the system: How is the agent identified ?

Just do:

curl -XPOST -H "Content-Type: application/json" \
	       -H "Authorization: Bearer <ACCESS_TOKEN>" \
	         https://bbp.epfl.ch/nexus/v0/queries/your_project?from=20&size=20' \
     	       -d '{"@context":"https://bbp.epfl.ch/nexus/v0/contexts/neurosciencegraph/core/data/v0.3.2","filter":{"op":"eq","path":"schema:email ","value":" ying.shi@epfl.ch"}, "resource": "instances", "deprecated": "false"}'

5. Keep in mind that the only user identification element we have on the software is the authentication token.

It is the responsibility of the person who bring data in Nexus to create all necessary entities, activities and agents to describe the provenance of his/her data. If you want to store data in Nexus and describe the fact that Ying generated it using a software then you need to create agents in Nexus describing Ying and the software.

Of course, a better solution would be to get the software you are using integrated with Nexus by automatically extracting user info from a token and registering in Nexus the corresponding agent.


Best.

**Comment by samuel-kerrien** [comment]
Thank you for the answer. My conclusion is the following:

1- the user is identified uniquely by the email.

2- prior to V1, there can be duplication.

3- I think you should provide a service that returns and eventually creates an agent based on a given token as this will be a very common operation and I would be afraid that agents are not registered consistently:

Let's take one agent: you registered "Caroline Violot". With attribute "given name" being "Caroline". Unfortunately, LDAP gives me "givenName: Caroline Camille Sophie". This is already a different value... And then you can say I should parse that and take the first one but then there are exceptions and we already faced that in the past with HBP platforms, see https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/. 
I don't want every piece of code to implement that thing.

Regards,
Jean-Denis

**Comment by samuel-kerrien** [comment]
Genrich Ivaska:

Why not using `preferred_username` for identification? Isn't it suppose to be unique in the context bbp/hbp?

**Comment by samuel-kerrien** [comment]
Francois:

Hi,
 
Your conclusions 1 and 2 below are correct. The unique identifier of an agent will change after we release Nexus v1 as emails are not persistent (think of people that change labs and affiliations and therefore emails). We will need to meet and discuss about the best way of identifying people in BBP (gaspar, …) and how to store that in Nexus.
 
3- I think you should provide a service that returns and eventually creates an agent based on a given token as this will be a very common operation and I would be afraid that agents are not registered consistently:

We are fully aware that agents’ identifiers need to all conform to the same pattern and preferably generated in the same way. And having a dedicated tool/service to do that is a must. The dedicated tool/service should be able to take a token or any other identifier we come up with and resolve (using different criteria) the corresponding agent in Nexus:
If the agent is already in Nexus then reuse it
If it is a new agent then create it
 
It is a tool/service we need anyway for the experimental data we integrate. I propose we meet after the release of Nexus v1 (in July then) to agree on:
how to identifier an agent in BBP. We have some ideas and we’ll make proposal prior to that meeting
what tool or service (python api, REST service) to offer?
 
Best.

**Comment by umbreak** [comment]
There can be a difference between the person who pushes the data in nexus and the person who actually produced the data (provenance). The later should be expressed as provenance in the instance metadata. The first should be provided by Nexus (v1).

There should be unicity provided by the OIDC provider by the fields `realm` + `sub`:
```bash
curl -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" "https://bbp-nexus.epfl.ch/staging/v0/oauth2/user" | jq '.' | grep -B 2 -A 3 "UserRef"
```
This information is present on our primary store. We just have to find a meaningful triples to add this to every instance. Once done, it can be queries regularly.

Would it be useful @genric @samuel-kerrien @MFSY ?

**Comment by genric** [comment]
Of course :) Auditing info has to be done by the data management system and it has to be immutable and available to the users in the triples form. Also it has to populate and maintain user list based on userinfo+token extracted info if you don't want to sync users with LDAP/...

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/104)
