### ISSUE TITLE
Permissions based on resource type?

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#430]
Permissions which are used right now on kg
- resources/read
- resources/write
- resources/create
- resources/manage

In Admin:
- projects/read
- projects/write
- projects/create
- projects/manage
- orgs/read
- orgs/write
- orgs/create
- orgs/manage

I guess we would like to control permissions in KG in a more granular way than just `resources`. Maybe we want to add:
- resolvers/{read|write|create|manage}
- schemas/{read|write|create|manage}
- views/{read|write|create|manage}

**UPDATED: No hierarchy.**
<del>I understand that there is an implicit hierarchy on it, meaning that if a client has `resources/read` he/she can also read `resolvers`, `schemas` and `views`. While if he/she has only `resolvers/read` he cannot read any other resource.

Is that correct? Any comments @bogdanromanx @wwajerowicz ?

**Comment by bogdanromanx** [comment]
I agree we need more granular permission types, but I'd put this on v1.1 milestone.

**Comment by bogdanromanx** [comment]
I would say specific resource types require specific permissions (accounts/projects/schemas/resolvers/views) and should not be included in `resources`.

**Comment by bogdanromanx** [comment]
> one could think that "anything" is a resource
That is in fact the case, but I think it's reasonable that operations on certain resource types require different or additional permissions.
