### ISSUE TITLE
Default views and resolvers

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#489]
When a project gets created those resources get added to the cache
- Default `ElasticView`
- Default `SparqlView`
- Default `InProjectResolver`

Right now those are volatile resources, not stored in the primary store. They can be listed because we access the cache to list them instead of the elasticsearch index (as done for any other resource).

The advantage of having them volatile is that those resources are not manageable (they cannot be deprecated, updated, ...).

However, there is an inconsistency here. When listing resources `/v1/resources/{org}/{proj}` those resources will not appear as response. But when listing resources through `/v1/views/{org}/{proj}` or `/v1/views/{org}/{proj}/nxs:view` they will.

What we could do is:
- When a project gets created, create the default resources on the primary store if they do not exist already.
- Prevent any modification of the lifecycle of those resources.
Thoughts?

**Comment by bogdanromanx** [comment]
The problem with creating these resources on the primary store is that if we need to change their structure we will have to run migration scripts during the deployment; this concerns me a bit because it's a high price to pay. If we do decide to go down this path, for which I'm quite sure it's the right one, I recommend defining an appropriate permission and making use of IAM to block operations that should be discouraged.

**Comment by umbreak** [comment]
Isn't a publication of a resource (something we didn't tackle yet) exactly that: a way to freeze the resource to a particular state and do not allow any further writing operations on it?

The granularity we have on permissions doesn't allow us to have those restrictions based on ACLs
If we set `resolvers/read` and `resolvers/create` permissions on a certain project, no resolver can be updated/deprecated/... on that project. And we want to apply this only to the default resolver.

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/86)
