### ISSUE TITLE
/v1/views/{org}/{proj}/nxv:defaultSparqlIndex/sparql expects wrong content type

### ISSUE THREAD

**Issue by wwajerowicz** [BlueBrain/nexus-kg#503]
`/v1/views/{org}/{proj}/nxv:defaultSparqlIndex/sparql` expects `application/json` 
Therefore the only way to send the query is to send JSON string (with quotes) with `Content-Type` header set to `application/json`.
According to this [document](https://www.w3.org/TR/sparql11-protocol/#query-via-post-direct), the `Content-Type` of the request should be `application/sparql-query`.

**Comment by umbreak** [comment]
Very strange that it expects `applcation/json` if the unit test is made passing a string and [this line](https://github.com/BlueBrain/nexus-kg/blob/master/src/main/scala/ch/epfl/bluebrain/nexus/kg/routes/ResourcesRoutes.scala#L103) is using `entity(as[String])`. Maybe the routes are not hitting that endpoint, but some other.

**Comment by wwajerowicz** [comment]
in the test on [this line](https://github.com/BlueBrain/nexus-kg/blob/f99eeb93c73a978b269b881cf53b91605cae63d2/src/test/scala/ch/epfl/bluebrain/nexus/kg/routes/ResourceRoutesSpec.scala#L606), it uses implicit JSON encoder, so it is marshalled into JSON. That's why the test works. And in the routes it uses the implicit string JSON decoder from `circe` to unmarshall the JSON string to regular string.
