### ISSUE TITLE
Support partial update across all resources in KG

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus-kg#53]
Implement the ability to partially update all resources in KG using the `PATCH` verb, as per https://tools.ietf.org/html/rfc5789. Content negotiation should discriminate between styles of partial updates (i.e.: simple overwrite or formal description of changes).

**Comment by pafonta** [comment]
@bogdanromanx 

1. Will this feature let a user change only for a resource - ie. without needing to retrieve the whole payload before, modify it, and submit it again - the value of a property or add a property and its value?

2. What would be the behaviour regarding resource validation?

**Comment by pafonta** [comment]
@umbreak So, if I understand correctly, the answer to 1. is 'yes'. Concerning 2., I imagine that the first time the entity payload is pushed, it should go through the validation, doesn't it? If yes, would it be possible to temporary deactivate it in a special case?

**Comment by umbreak** [comment]
1. Yes
2. Every time there is a creation, update, partial update, the validation gets triggered. It would be possible to avoid validation...but why? :)

**Comment by bogdanromanx** [comment]
1. In order to perform a partial update you'd still have to provide the latest revision; this is to protect the user from incorrectly updating a resource (the miss update issue)
2. We always have to run the validation when changes happen. There are no exceptions.

**Comment by pafonta** [comment]
@umbreak 
To avoid validation errors when IDs of linked entities are not yet available. However, it seems that this use case will disappear with v1 and user provided IDs. There could be some other considerations but not need to talk about them now.

@bogdanromanx 
Regarding 1., this means that it would still be needed to get the whole payload of the resource from Nexus? Or could it be assumed that if nobody will update the data, using "1" as the latest revision will be OK?

**Comment by umbreak** [comment]
Kamino closed and cloned this issue to [BlueBrain/nexus](https://github.com/BlueBrain/nexus/issues/109)
