### ISSUE TITLE
Add JSON-LD support on HTTP requests-responses

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#54]
The [documentation](https://bbp-nexus.epfl.ch/dev/docs/kg/api-reference/organizations.html) correctly defines the HTTP format that has to be used in the HTTP requests and returned in the responses.

However, in many the cases we are not using  the context right now, neither having proper JSON-LD predicates.

**Comment by wwajerowicz** [comment]
I understand we can do this in two ways:
either we always add 
`"nxv": "https://nexus.example.com/v0/voc/nexus/core/"` to the context:
```
{
  "@context": {
    (...)
    "nxv": "https://nexus.example.com/v0/voc/nexus/core/"
  }
}
```
and rename the keys from the the returned objects from `rev`, `deprecated` to `nxv:rev`, `nxv:deprecated` etc.
or we can add something like that to the context:
```
{
  "@context": {
    (...)
    "nxv": "https://nexus.example.com/v0/voc/nexus/core/",
    "rev": {
      "@id": "nxv:rev"
    },
    "deprecated": {
      "@id": "nxv:deprecated"
    }
  }
}
```
the benefit of the latter being that the current JSON payload keys would stay the same.

What do you think @MFSY  @umbreak @hygt ?

**Comment by umbreak** [comment]
We are going to have a context resource where we define all the nexus specific triples and then we can have something like
```
{
  "@context": "https://example.com/v0/contexts/nexus/core/resource/v1.0.0"
}
```
and keeping our payload the same way how it is now. So indeed is like the second option described by @wwajerowicz but with externalized context
