### ISSUE TITLE
Allow valid JSON-LD payload on domain metadata

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#55]
Right now domain metadata is fixed to `{"description": "some_description"}`. I think there is no real reason for it. 
To be consistent, it should allow any valid JSON-LD metadata (like the rest of resources).

**Comment by MFSY** [comment]
Organisation and domain should have dedicated (fixed and versioned) schemas in nexus. The two schemas will be part of the Nexus core schemas  #20

**Comment by umbreak** [comment]
Probably we are not going to tackle this issue for `v0`. For `v1` we will have payload on the context level (context mappings, resolvers for external "repos", etc)
