### ISSUE TITLE
Provide more discoverability through HATEOAS

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#56]
More discoverability can be provided through those relationships.

One case would be to add a `attachment` relationship for an instance with attachment.
This is only one example and there are certainly some other useful relationships. @bogdanromanx @MFSY @wwajerowicz some thoughts about it?

**Comment by bogdanromanx** [comment]
Agreed. I would recommend tracking these through different specific issues.

**Comment by umbreak** [comment]
Yes. This issue is mostly to discuss and group in a common place which relationships we want to add and where. Afterwards we can create a ticket for each of them.

**Comment by MFSY** [comment]
I would start by 'history' (to get the revisions) and 'provenance' (to get a description of the provenance).
The right context needs to be provided for these relations so that they are valid property URIs. They fall under the nexus base namespace (to be defined in relation with #27  ).

**Comment by MFSY** [comment]
"incoming" and "outgoing" relations are natural candidates.
Schemas can have "shapes" relations to list the shapes they define.

**Comment by mdupont** [comment]
"schema" with a link to the schema for the entity

**Comment by umbreak** [comment]
@mdupont schema is already part of the discoverability `links`
