### ISSUE TITLE
Add `sort` query param to describe the sorting criteria when querying data

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/nexus-kg#57]
the query API [](https://bbp-nexus.epfl.ch/dev/docs/kg/api-reference/instances.html#full-text-search) allows to define a filter.
However one cannot specify how the results are sorted.
Let's say I want to display my model sorted by alphabetic order of their name. I cannot do that if there is pagination involved.

**Comment by umbreak** [comment]
The default sorting strategy is by `resourceId` ascending.

However I agree we would have to come up with some other customize sorting options.

**Comment by bogdanromanx** [comment]
Good ticket! I'll add this to the backlog.

**Comment by genric** [comment]
I think it makes more sense to order by create/update date descending by default. As I'd prefer to get with the request the most recent entities first. Just an opinion :)
