### ISSUE TITLE
Towards a dataset description in Nexus KG

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus-kg#59]
It may be useful to have a domain-independent way of describing dataset metadata in nexus:
 - dataset identifiers: doi, ..
 - dataset types and keywords
 - license, rights
 - provenance: creator,...
 - data download information
 - ...

A lof of specs are already available: [schema.org/Dataset](http://schema.org/Dataset) heavily based on [w3c dcat](https://www.w3.org/TR/vocab-dcat/).

Two use cases can occurs:
 - a nexus user can submit a dataset without having to write a single schema: as long as types and keywords (from controlled vocabularies) are provided the semantic search can still occurs
 - an instance describing a dataset in a domain specific way can be migrated to match the nexus dataset description.

Thoughts ?

**Comment by slhill** [comment]
I think it's a good idea - you might also look at Biocaddie for examples.

**Comment by MFSY** [comment]
Thank you @slhill . I'll definitely have a look at it.

**Comment by MFSY** [comment]
Hi @bogdanromanx,
Yes the client will have to select the schema and make the necessary calls to submit data.
