### ISSUE TITLE
Context support: Create resource endpoints

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#66]
This is a sub issue from the generic one #16 .
The endpoints and operations should be as the ones for schemas

**PUT** `/context/{org}/{dom}/{context_name}/{context_version}` -> creates a new context
**PUT** `/context/{org}/{dom}/{context_name}/{context_version}?rev={prev_revision}` -> updates an existing context
**PATCH** `/context/{org}/{dom}/{context_name}/{context_version}/config?rev={prev_revision}` (with the JSON payload `{"published": true}` -> publish a context
**GET** `/context/{org}/{dom}/{context_name}/{context_version}` -> fetches the latest revision of a context
**GET** `/context/{org}/{dom}/{context_name}/{context_version}?rev={rev}` -> fetches a specific revision of a context
**DELETE** `/context/{org}/{dom}/{context_name}/{context_version}?rev={rev}` -> deprecates a context (no new schema can refer to it)

**Comment by wwajerowicz** [comment]
fixed by #87
