### ISSUE TITLE
Add support for search resources using the POST verb

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#77]
Right now we are using the `GET` verb with query parameters for search resources.
We want to add support using search through `POST` verb.

**Comment by umbreak** [comment]
Here is a proposal of the `POST` on `/v0/search/{collection_address}`
```json
{
  "@context": "nexus.example.ch/context/some",
  "filter": {
    "path": "nxv:deprecated",
    "op": "eq",
    "value": false
  },
  "fullText": "someText",
  "fields": [ "one", "two", "three", "four" ],
  "sortBy": [ "one", "-two",  "+three" ],
  "from": 0,
  "size": 10,
  "deprecated": false
}
```

Thoughts @hygt @bogdanromanx ?

**Comment by bogdanromanx** [comment]
I think the payload looks good, but the address I think should constructed based on the current selection, for example:
`/v0/data/{org}/query`
or
`/v0/schemas/query`
or
`/v0/schemas/{org}/{dom}/query`
... such that we can still make use of the partial address.

I'm thinking if we should also rename `fullText` to `q` or `query`.

**Comment by umbreak** [comment]
Discussing about it we arrived to the following idea:

## Request
`POST` `/v0/queries/{org}/{dom}/...`
```json
{
  "@context": "nexus.example.ch/context/some",
  "filter": {
    "path": "nxv:deprecated",
    "op": "eq",
    "value": false
  },
  "q": "someText",
  "resource": "data|schemas|contexts|domains|organizations",
  "deprecated": false,
  "expand": false,
  "fields": [ "all" ],
  "sortBy": [ "one", "-two",  "+three" ],
  "from": 0,
  "size": 10,
}
```

## Response
The server will store the query, generate a UUID for it and respond with `HTTP 303 (See other)`
The browser will then perform `GET` `/v0/queries/{id}`, which will result in:
```json
{
  "@context": "https://nexus.example.com/dev/v0/contexts/nexus/core/search/v0.1.0",
  "total": 10,
  "results": [
    {
      "source": {
        "@id": "https://nexus.example.com/dev/v0/schemas/bbp/core/activity/v0.1.0"
      }
    },
    {
      "source": {
        "@id": "https://nexus.example.com/dev/v0/schemas/bbp/core/agent/v0.1.0"
      }
    }
  ],
  "links": {
    "@context": "https://nexus.example.com/dev/v0/contexts/nexus/core/links/v0.1.0",
    "next": "https://nexus.example.com/dev/v0/queries/{id}?from=2&size=2",
    "self": "https://nexus.example.com/dev/v0/queries/{id}"
  }
}
``` 

With this solution we store each query on the platform. That allow us to reference the query to make it resolvable on the links `next` and `previous`. It can potentially be used for `saved user queries`. In the future we could make us of it to deal with `slow queries`.
