### ISSUE TITLE
Unify support for from, size, filter and text query parameters across all listings

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus-kg#8]
Every listing on the system should support a combination of the following HTTP query parameters:

- **from**: Starting offset
- **size**: Amount of results retrieved
- **filter**: Logical & Comparison expression filter (e.g.: (a = b) && ( c != b) )
- **text**: Full text search query on an object

**Comment by bogdanromanx** [comment]
We also need to be able to list instances and schemas without specifying an origin organization:

```
GET /data?q=text&filter={"op":"gt","path":"nxv:rev","value":0}
```

Could we include that work here?
